name: Ignis Dolphin Builder

on: [push, pull_request]

jobs:
  build_windows_x86_64:
    name: Windows Build
    runs-on: windows-2022
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        repository: Maye1918/Ignis
        ref: master
        fetch-depth: 0
        submodules: recursive
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3
    - name: Build
      shell: pwsh
      run: |
        msbuild Source\dolphin-emu.sln `
          /m `
          /verbosity:normal `
          /p:Configuration=Release `
          /p:Platform=x64 `
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v7
      with:
        name: Ignis-Dolphin-Windows${{ env.DOLPHINVER }}
        path: Binary/x64/
